services:
  my-classifier-container:
    image: my-classifier:1.0
    build:
      context: .
      dockerfile: Docker/Dockerfile
    volumes:
      - .\data:/app/data
      - .\tensorboard:/app/tensorboard

  tensorboard:
    image: pccl/tensorboard
    ports:
      - "6006:6006"
    volumes:
      - .\tensorboard:/app/tensorboard
    command: tensorboard --logdir=/app/tensorboard --bind_all